name: container_server_example
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ^3.3.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2

dev_dependencies:
  http: ^1.2.0
  lints: ^3.0.0
  test: ^1.25.0
  test_process: ^2.1.0
